---
- name: Choose OS based tasks
  include_tasks: '{{ system_spec }}'
  with_first_found:
    - '{{ ansible_system }}/{{ ansible_distribution }}-{{ ansible_distribution_version[:1] }}.yml'
    - '{{ ansible_system }}/other.yml'
  loop_control:
    loop_var: system_spec

- name: Ensure pip_install_packages are installed.
  pip:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    virtualenv: "{{ item.virtualenv | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    executable: "{{ pip_executable }}"
  with_items: "{{ pip_install_packages }}"
