---
- name: Install packages for make python2.7
  yum:
    name:
      - gcc
      - openssl-devel
      - bzip2-devel
      - zlib-devel
    state: present
  register: package_install
  until: package_install is succeeded

- name: 'Download artifact from python.org'
  get_url:
    url: 'https://www.python.org/ftp/python/{{ centos6_python_version }}/Python-{{ centos6_python_version }}.tgz'
    dest: '/usr/src'
  register: file_downloaded
  retries: 2
  delay: 5
  until: file_downloaded is succeeded

- name: Set downloaded artifact variable
  set_fact:
    python_artifact: '{{ file_downloaded.dest }}'

- name: Create directory for python src
  file:
    path: '{{ python27_src_path }}'
    state: directory
    owner: root
    mode: 0755

- name: 'Unpack python {{ centos6_python_version }}'
  unarchive:
    src: '{{ python_artifact }}'
    dest: '{{ python27_src_path }}'
    remote_src: True
    owner: root
    group: root
    mode: 0755
    extra_opts: [--strip-components=1]
  register: python_source_unpack
  when: file_downloaded is changed

- name: Configuring Python2.7
  command: >-
    ./configure
    --enable-optimizations
    --with-zlib-dir=/usr/local/lib
    --with-openssl
  args:
    chdir: '{{ python27_src_path }}'
  when: python_source_unpack is changed
  register: python_configure

- name: Installing Python2.7
  command: make altinstall
  args:
    chdir: '{{ python27_src_path }}'
  when: python_configure is changed

- name: Install Pip
  include_tasks: '../python27_pip.yml'
  when:
    - centos6_python_pip_install
